### ISSUE TITLE
csv download is not quoted when keys contain separator "sep".

### ISSUE THREAD

**Issue by HanOostdijk** [statistiekcbs/cbsccb#3]
Edwin, 

when the `Value` field contains comma's in some result rows the default value for separator `sep` (a comma) gives a error. 

E.g.

`X=cbs4_get_observations('900003NED',catalog='CBS-asd', query="$filter=startswith(RegioS,'GM0362')",verbose = T) `

gives the following error (formally a warning but not all data is returned so the full operation is in error) :
```
Reading metadata from cache: C:\Users\Han\AppData\Local\Temp\RtmpkDpsMc/CBS-asd_900003NED.rds
Retrieving https://beta-odata4.cbs.nl/CBS-asd/900003NED/Observations?$filter=startswith(RegioS,'GM0362')
The data is in 'C:\Users\Han\AppData\Local\Temp\RtmpkDpsMc/900003NED'
Warning message:
In data.table::fread(file.path(download_dir, "Observations.csv"),  :
  Stopped early on line 158. Expected 8 fields but found 9. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<264667,M00001,None,GGD Amstelland, de Meerlanden,GG35,GG,GM0362,2004>>
```

This particular problem is solved by specifying in the function call e.g. `sep=';'`.

My questions: 

- should the documentation of the `sep` argument be more specific as to this possible problem?
- should the error message be analysed : expected x, found y with y > x then suggest a different separator. The `fread` suggests `Consider fill=TRUE and comment.char=. ` but the user has no influence on that.
- or is the error message  clear enough ?

**Comment by edwindj** [comment]
Thanks for reporting! 
This was a bug, my bad. When a value in a table contained a separator character the column was not "quoted". Since it is very rare that keys contain separators, I hadn't run into this issue.
